name: 'test-auto-deploy'

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
      - dev
  schedule:
    - cron: '10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # cache node_modules
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
          
      - name: auto gen Item_Features.js
      - shell: bash
        env: # Set the secret as an input
          qurey_url: ${{ secrets.SERVER_QUERY_URL }}
        run: |
          shell: bash 
          node ./tools/genGeoJson.mjs "$qurey_url"
          yes | cp -rf ./Item_Features.js ./Yuanshenditu/js/Item_Features.js
          tail -n 10 ./Yuanshenditu/js/Item_Features.js
      # 部署
      # - name: Deploy
      #   uses: easingthemes/ssh-deploy@v2.2.11
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
      #     # 删除服务器上目录里所有文件
      #     # ARGS: '-avz --delete'
      #     # 部署目录
      #     SOURCE: 'Yuanshenditu/'
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.TARGET }}
      #     EXCLUDE: "/node_modules/"
